name: trippify
description: "A group travel companion app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  firebase_core: ^4.1.1
  provider: ^6.1.5+1
  firebase_auth: ^6.1.0
  get_it: ^8.2.0
  lottie: ^3.3.1
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/jsons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
