name: Flutter Build & Upload

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter clean
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Analyze code
        run: flutter analyze
        continue-on-error: true

      - name: Run tests
        run: flutter test
        continue-on-error: true

      - name: Build release APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apks
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 30

      - name: Upload to Google Drive
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: build/app/outputs/flutter-apk/app-release.apk
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          name: trippify-${{ github.sha }}.apk
